"""Tests for ecomm.protocol.compute.

The parametrized wire-vector test below was generated by compiling and
running the real ``ecomm::protocol::compute<ChecksumPolicy>`` specializations
from ``ecomm/protocol/compute.hpp`` against a fixed 37-byte buffer (37 is
deliberately odd, to exercise the tail-byte handling in fletcher32 and
internet16). Any regression here that diverges from the C++ side would
silently break wire interop, so these are pinned literal values rather than
self-referential round-trip checks.
"""

import pytest

from ecomm.protocol.checksum import ChecksumPolicy
from ecomm.protocol.compute import compute_checksum

_TEST_BUFFER = bytes((i * 7 + 3) & 0xFF for i in range(37))

_CPP_REFERENCE_VALUES = {
    ChecksumPolicy.SUM8: 165,
    ChecksumPolicy.SUM16: 4773,
    ChecksumPolicy.SUM32: 4773,
    ChecksumPolicy.CRC8: 20,
    ChecksumPolicy.CRC16: 52380,
    ChecksumPolicy.CRC32: 2843316199,
    ChecksumPolicy.CRC64: 488403455590511774,
    ChecksumPolicy.FLETCHER16: 55479,
    ChecksumPolicy.FLETCHER32: 4275444636,
    ChecksumPolicy.ADLER32: 4010676902,
    ChecksumPolicy.INTERNET16: 58977,
}


@pytest.mark.parametrize("policy", list(_CPP_REFERENCE_VALUES.keys()))
def test_matches_cpp_reference_value(policy):
    """Every non-NONE policy must match ecomm::protocol::compute<> bit-for-bit."""
    assert compute_checksum(policy, _TEST_BUFFER) == _CPP_REFERENCE_VALUES[policy]


@pytest.mark.parametrize("policy", list(_CPP_REFERENCE_VALUES.keys()))
def test_result_fits_wire_width(policy):
    assert 0 <= compute_checksum(policy, _TEST_BUFFER) < policy.max_value


def test_empty_buffer_does_not_crash():
    for policy in _CPP_REFERENCE_VALUES:
        compute_checksum(policy, b"")


def test_none_policy_is_rejected():
    with pytest.raises(Exception):
        compute_checksum(ChecksumPolicy.NONE, _TEST_BUFFER)


def test_single_bit_flip_changes_every_algorithm():
    """Sanity check: flipping one bit must change the checksum (not a proof of
    detection strength, just a guard against an accidentally constant function).
    """
    corrupted = bytearray(_TEST_BUFFER)
    corrupted[10] ^= 0x01
    for policy in _CPP_REFERENCE_VALUES:
        assert compute_checksum(policy, bytes(corrupted)) != compute_checksum(policy, _TEST_BUFFER)
